# Usage:
# python doistemplate.py templates/recipe.yml -D title="crepe alla nutella",date="saturday"

Diy:
  sections:
    -
      name: "Cook"
      tasks:
        -
          content: "ricetta: {title}"
          due_string: "{date}"

Home:
  sections:
    -
      name: "Purchase"
      tasks:
        -
          content: "spesa per {title}"
          due_string: "{date}"
          labels: ["purchase"]