# Usage:
# python doistemplate.py templates/recipe.yml -D title="crepe alla nutella",date="saturday"

Diy:
  sections:
    -
      name: "Cook"
      tasks:
        -
          content: "{title}"
          due_string: "{date}"
          tasks:
            -
              content: "spesa"
              description: "spesa per {title}"
